name: Publish to OpenVSX Registry

on:
  # TODO: Enable auto-publish
  # workflow_run:
  #   workflows: ["Create Release Artifacts"]
  #   types: [completed]
  #   branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    if: ${{ github.event_name == 'workflow_dispatch' }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: npm ci

    - name: Publish to OpenVSX Registry
      env:
        OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
      run: |
        echo "Publishing to OpenVSX Registry..."
        npx ovsx publish -p $OVSX_TOKEN 