name: Create Release Artifacts

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  create-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      uses: coactions/setup-xvfb@v1
      with:
        run: npm test

    - name: Run linter
      run: npm run lint

    - name: Update version in package.json
      run: |
        # Extract version from tag or manual input
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION=${{ github.event.inputs.tag_name }}
          VERSION=${VERSION#v}  # Remove 'v' prefix if present
        else
          VERSION=${GITHUB_REF#refs/tags/v}
        fi
        echo "Setting version to $VERSION"
        
        # Get current version from package.json
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "Current version in package.json: $CURRENT_VERSION"
        
        # Only update version if it's different
        if [ "$CURRENT_VERSION" != "$VERSION" ]; then
          echo "Updating version from $CURRENT_VERSION to $VERSION"
          npm version $VERSION --no-git-tag-version
          
          # Commit updated package.json back to repository
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m "Update version to $VERSION [skip ci]" || exit 0
          git push origin HEAD:main
        else
          echo "Version is already $VERSION, skipping update"
        fi

    - name: Package extension
      run: |
        npm install -g vsce
        vsce package
        echo "Generated VSIX files:"
        ls -la *.vsix

    - name: Find VSIX file
      id: find_vsix
      run: |
        VSIX_FILE=$(ls *.vsix | head -1)
        echo "Found VSIX file: $VSIX_FILE"
        echo "vsix_file=$VSIX_FILE" >> $GITHUB_OUTPUT
        echo "vsix_path=$(pwd)/$VSIX_FILE" >> $GITHUB_OUTPUT

    - name: Upload VSIX to Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.find_vsix.outputs.vsix_path }}
        tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name || github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }} 